globalThis.PAGE_I18N = {
  'zh-CN': { title:'Extract page info with one click', subtitle:'把网页变成可直接使用的信息', insight:'提取重要信息', insightHint:'标题、主题、摘要、关键段落和链接', page:'复制当前页面', pageHint:'复制清理后的完整正文', selection:'复制选中内容', selectionHint:'保留你当前选中的文字', shortcut:'快捷键', shortcutText:'Ctrl / ⌘ + Shift + I 提取信息 · Ctrl / ⌘ + Shift + Y 复制页面', privacy:'内容只在本地处理，不上传页面数据', copied:'已成功复制到剪贴板', copyFailed:'复制失败，请重试或检查浏览器权限', none:'当前页面没有选中文本', insightPrefix:'页面速览', url:'网址', summary:'一句话简介', topics:'关键主题', passages:'正文要点', links:'相关链接', copySelection:'复制选中内容', selectionCopied:'✓ 已复制', selectionFailed:'! 复制失败' },
  en: { title:'Extract page info with one click', subtitle:'Turn any page into usable information', insight:'Extract key information', insightHint:'Title, topics, summary, passages and links', page:'Copy current page', pageHint:'Copy a cleaned version of the page', selection:'Copy selection', selectionHint:'Keep the text you selected', shortcut:'Shortcuts', shortcutText:'Ctrl / ⌘ + Shift + I extract · Ctrl / ⌘ + Shift + Y copy page', privacy:'Processed locally. Page data is never uploaded.', copied:'Copied to clipboard', copyFailed:'Copy failed. Try again or check browser permissions.', none:'No text is selected', insightPrefix:'Page Insight', url:'URL', summary:'Summary', topics:'Key topics', passages:'Key passages', links:'Useful links', copySelection:'Copy selection', selectionCopied:'✓ Copied', selectionFailed:'! Copy failed' },
  ja: { title:'Extract page info with one click', subtitle:'ページを使える情報に変換', insight:'重要情報を抽出', insightHint:'タイトル、テーマ、要約、本文、リンク', page:'現在のページをコピー', pageHint:'整理した本文をコピー', selection:'選択範囲をコピー', selectionHint:'選択したテキストを保持', shortcut:'ショートカット', shortcutText:'Ctrl / ⌘ + Shift + I 抽出 · Ctrl / ⌘ + Shift + Y コピー', privacy:'ローカル処理。ページデータは送信されません。', copied:'クリップボードにコピーしました', copyFailed:'コピーに失敗しました。再試行してください。', none:'テキストが選択されていません', insightPrefix:'ページ速覧', url:'URL', summary:'概要', topics:'主なテーマ', passages:'本文の要点', links:'関連リンク', copySelection:'選択範囲をコピー', selectionCopied:'✓ コピーしました', selectionFailed:'! コピーに失敗しました' },
  ko: { title:'Extract page info with one click', subtitle:'웹 페이지를 바로 쓸 수 있는 정보로 변환', insight:'핵심 정보 추출', insightHint:'제목, 주제, 요약, 본문, 링크', page:'현재 페이지 복사', pageHint:'정리된 본문 복사', selection:'선택 영역 복사', selectionHint:'선택한 텍스트 유지', shortcut:'단축키', shortcutText:'Ctrl / ⌘ + Shift + I 추출 · Ctrl / ⌘ + Shift + Y 페이지 복사', privacy:'로컬에서 처리되며 페이지 데이터는 업로드되지 않습니다.', copied:'클립보드에 복사했습니다', copyFailed:'복사에 실패했습니다. 다시 시도하세요.', none:'선택된 텍스트가 없습니다', insightPrefix:'페이지 인사이트', url:'URL', summary:'요약', topics:'주요 주제', passages:'핵심 문단', links:'관련 링크', copySelection:'선택 영역 복사', selectionCopied:'✓ 복사됨', selectionFailed:'! 복사 실패' },
  es: { title:'Extract page info with one click', subtitle:'Convierte cualquier página en información útil', insight:'Extraer información clave', insightHint:'Título, temas, resumen, pasajes y enlaces', page:'Copiar página actual', pageHint:'Copiar el texto limpio', selection:'Copiar selección', selectionHint:'Conservar el texto seleccionado', shortcut:'Atajos', shortcutText:'Ctrl / ⌘ + Shift + I extraer · Ctrl / ⌘ + Shift + Y copiar página', privacy:'Procesado localmente. Los datos no se suben.', copied:'Copiado al portapapeles', copyFailed:'No se pudo copiar. Inténtalo de nuevo.', none:'No hay texto seleccionado', insightPrefix:'Resumen de página', url:'URL', summary:'Resumen', topics:'Temas clave', passages:'Pasajes clave', links:'Enlaces útiles', copySelection:'Copiar selección', selectionCopied:'✓ Copiado', selectionFailed:'! Error al copiar' },
  fr: { title:'Extract page info with one click', subtitle:'Transformez chaque page en informations utiles', insight:'Extraire les informations clés', insightHint:'Titre, thèmes, résumé, passages et liens', page:'Copier la page actuelle', pageHint:'Copier le texte nettoyé', selection:'Copier la sélection', selectionHint:'Conserver le texte sélectionné', shortcut:'Raccourcis', shortcutText:'Ctrl / ⌘ + Shift + I extraire · Ctrl / ⌘ + Shift + Y copier', privacy:'Traitement local. Les données ne sont jamais envoyées.', copied:'Copié dans le presse-papiers', copyFailed:'Échec de la copie. Réessayez.', none:'Aucun texte sélectionné', insightPrefix:'Aperçu de la page', url:'URL', summary:'Résumé', topics:'Thèmes clés', passages:'Passages clés', links:'Liens utiles', copySelection:'Copier la sélection', selectionCopied:'✓ Copié', selectionFailed:'! Échec de la copie' },
  de: { title:'Extract page info with one click', subtitle:'Jede Seite in nutzbare Informationen verwandeln', insight:'Wichtige Informationen extrahieren', insightHint:'Titel, Themen, Zusammenfassung, Absätze und Links', page:'Aktuelle Seite kopieren', pageHint:'Bereinigten Text kopieren', selection:'Auswahl kopieren', selectionHint:'Ausgewählten Text behalten', shortcut:'Tastenkürzel', shortcutText:'Ctrl / ⌘ + Shift + I extrahieren · Ctrl / ⌘ + Shift + Y kopieren', privacy:'Lokal verarbeitet. Seitendaten werden nicht hochgeladen.', copied:'In die Zwischenablage kopiert', copyFailed:'Kopieren fehlgeschlagen. Bitte erneut versuchen.', none:'Kein Text ausgewählt', insightPrefix:'Seitenüberblick', url:'URL', summary:'Zusammenfassung', topics:'Wichtige Themen', passages:'Wichtige Absätze', links:'Nützliche Links', copySelection:'Auswahl kopieren', selectionCopied:'✓ Kopiert', selectionFailed:'! Kopieren fehlgeschlagen' },
  pt: { title:'Extract page info with one click', subtitle:'Transforme qualquer página em informação útil', insight:'Extrair informações importantes', insightHint:'Título, temas, resumo, trechos e links', page:'Copiar página atual', pageHint:'Copiar texto limpo', selection:'Copiar seleção', selectionHint:'Manter o texto selecionado', shortcut:'Atalhos', shortcutText:'Ctrl / ⌘ + Shift + I extrair · Ctrl / ⌘ + Shift + Y copiar', privacy:'Processado localmente. Os dados não são enviados.', copied:'Copiado para a área de transferência', copyFailed:'Falha ao copiar. Tente novamente.', none:'Nenhum texto selecionado', insightPrefix:'Visão da página', url:'URL', summary:'Resumo', topics:'Temas principais', passages:'Trechos principais', links:'Links úteis', copySelection:'Copiar seleção', selectionCopied:'✓ Copiado', selectionFailed:'! Falha ao copiar' },
  ru: { title:'Extract page info with one click', subtitle:'Превратите страницу в полезную информацию', insight:'Извлечь важную информацию', insightHint:'Заголовок, темы, краткое содержание, текст и ссылки', page:'Копировать страницу', pageHint:'Копировать очищенный текст', selection:'Копировать выделение', selectionHint:'Сохранить выделенный текст', shortcut:'Сочетания клавиш', shortcutText:'Ctrl / ⌘ + Shift + I извлечь · Ctrl / ⌘ + Shift + Y копировать', privacy:'Обработка выполняется локально. Данные не загружаются.', copied:'Скопировано в буфер обмена', copyFailed:'Не удалось скопировать. Попробуйте ещё раз.', none:'Текст не выделен', insightPrefix:'Обзор страницы', url:'URL', summary:'Краткое содержание', topics:'Основные темы', passages:'Ключевые фрагменты', links:'Полезные ссылки', copySelection:'Копировать выделение', selectionCopied:'✓ Скопировано', selectionFailed:'! Ошибка копирования' }
};

globalThis.resolvePageLanguage = requested => {
  const browser = (navigator.language || 'en').toLowerCase();
  if (requested && requested !== 'auto' && PAGE_I18N[requested]) return requested;
  if (browser.startsWith('zh')) return 'zh-CN';
  if (browser.startsWith('ja')) return 'ja';
  if (browser.startsWith('ko')) return 'ko';
  if (browser.startsWith('es')) return 'es';
  if (browser.startsWith('fr')) return 'fr';
  if (browser.startsWith('de')) return 'de';
  if (browser.startsWith('pt')) return 'pt';
  if (browser.startsWith('ru')) return 'ru';
  return 'en';
};
